server:
  port: 8080
spring:
  datasource:
    druid:
      user:
        name: user-datasource
        url: jdbc:mysql://localhost:3306/seata_1?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 10
        minIdle: 5
        maxActive: 20
        maxWait: 3000
        timeBetweenEvictionRunsMillis: 2000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        validationQuery: select 1
        filter:
          stat:
            enabled: true
          wall:
            enabled: true
            throw-exception: false
      order:
        name: order-datasource
        url: jdbc:mysql://localhost:3306/seata_2?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 10
        minIdle: 5
        maxActive: 20
        maxWait: 3000
        timeBetweenEvictionRunsMillis: 2000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        filter:
          stat:
            enabled: true
          wall:
            enabled: true
            throw-exception: false
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
      stat-view-servlet:
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 10.254.1.1/24,10.1.128.1/24
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          throw-exception: false
logging:
  config: classpath:logback-dev.xml


seata:
  enabled: true
  application-id: test
  tx-service-group: my_test_tx_group
  client:
    rm-async-commit-buffer-limit: 1000
    rm-report-retry-count: 5
    rm-table-meta-check-enable: false
    rm-report-success-enable: true
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-times: 30
        lock-retry-policy-branch-rollback-on-conflict: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    support:
      spring:
        datasource-autoproxy: true
    undo:
      undo-data-validation: true
      undo-log-serialization: jackson
      undo-log-table: undo_log
    client:
      log:
        exceptionRate: 100
